//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atom.Main {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atom.Main.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CF942F4C-5F93-42DE-8703-CD1BF85193F5.
        /// </summary>
        internal static string FusionAuthKey_BeValuedCMS {
            get {
                return ResourceManager.GetString("FusionAuthKey_BeValuedCMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9974E010-6DD8-484D-8BD0-EAAC9BA01DBE.
        /// </summary>
        internal static string FusionAuthKey_BeValuedFNOL {
            get {
                return ResourceManager.GetString("FusionAuthKey_BeValuedFNOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B7AFE6A5-77CC-464A-B1E3-4DC4D20A2B7C.
        /// </summary>
        internal static string FusionAuthKey_BeValuedTS {
            get {
                return ResourceManager.GetString("FusionAuthKey_BeValuedTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 77D0EC02-1B63-4D23-9632-F90B60A6045E.
        /// </summary>
        internal static string FusionAuthKey_BeValuedValidator2 {
            get {
                return ResourceManager.GetString("FusionAuthKey_BeValuedValidator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0caC_ola.
        /// </summary>
        internal static string FusionAuthPW_BeValuedCMS {
            get {
                return ResourceManager.GetString("FusionAuthPW_BeValuedCMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jAckDan1elS.
        /// </summary>
        internal static string FusionAuthPW_BeValuedFNOL {
            get {
                return ResourceManager.GetString("FusionAuthPW_BeValuedFNOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ba1LeyS.
        /// </summary>
        internal static string FusionAuthPW_BeValuedTS {
            get {
                return ResourceManager.GetString("FusionAuthPW_BeValuedTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr_PeP3r.
        /// </summary>
        internal static string FusionAuthPW_BeValuedValidator2 {
            get {
                return ResourceManager.GetString("FusionAuthPW_BeValuedValidator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeValued.CMS.
        /// </summary>
        internal static string FusionAuthUser_BeValuedCMS {
            get {
                return ResourceManager.GetString("FusionAuthUser_BeValuedCMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeValued.FNOL.
        /// </summary>
        internal static string FusionAuthUser_BeValuedFNOL {
            get {
                return ResourceManager.GetString("FusionAuthUser_BeValuedFNOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeValued.TS.
        /// </summary>
        internal static string FusionAuthUser_BeValuedTS {
            get {
                return ResourceManager.GetString("FusionAuthUser_BeValuedTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeValued.Validator2.
        /// </summary>
        internal static string FusionAuthUser_BeValuedValidator2 {
            get {
                return ResourceManager.GetString("FusionAuthUser_BeValuedValidator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is a required field.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role successfully added.
        /// </summary>
        internal static string RoleAddSuccess {
            get {
                return ResourceManager.GetString("RoleAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role and username were not supplied.
        /// </summary>
        internal static string RoleAndUserNotSupplied {
            get {
                return ResourceManager.GetString("RoleAndUserNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role successfully removed.
        /// </summary>
        internal static string RoleRemovalSuccess {
            get {
                return ResourceManager.GetString("RoleRemovalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not added successfully.
        /// </summary>
        internal static string UserAddFail {
            get {
                return ResourceManager.GetString("UserAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added successfully.
        /// </summary>
        internal static string UserAddSuccess {
            get {
                return ResourceManager.GetString("UserAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId was not supplied.
        /// </summary>
        internal static string UserIDNotPresent {
            get {
                return ResourceManager.GetString("UserIDNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either your username or password is incorrect.
        /// </summary>
        internal static string UsernameOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is a required field.
        /// </summary>
        internal static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not removed successfully.
        /// </summary>
        internal static string UserRemovalFail {
            get {
                return ResourceManager.GetString("UserRemovalFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User removed successfully.
        /// </summary>
        internal static string UserRemovalSuccess {
            get {
                return ResourceManager.GetString("UserRemovalSuccess", resourceCulture);
            }
        }
    }
}
